### ISSUE TITLE
Doc update, UBL Credit Note ubl:CreditNote cac:PaymentMeans

### ISSUE THREAD

**Issue by stoivo** [difi/ehf-postaward-g3#3]
Hei, 
Ikke helt sikker på hvor dette burde rapporteres, men jeg vet dere vet :D

Det ser ut som om jeg har funnet en feil i dokumentasjonen. Per https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-creditnote/cac-PaymentMeans/ ser det ut som om  en `ubl:CreditNote -> cac:PaymentMeans` kan ha 0..1 `cbc:PaymentDueDate`. Invoice dok'n https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-PaymentMeans/ har ikke `cbc:PaymentDueDate`.

Validatoren sier `/cn:CreditNote[1],  Test: not(cac:PaymentMeans/cbc:PaymentDueDate)`

**Comment by stoivo** [comment]
ping

**Comment by klakegg** [comment]
Ser ut til å være knyttet til PEPPOL BIS og ikke EHF.
