### ISSUE TITLE
Include is pointing to a reference that does not exist in EHF-REMINDER-3.0.sch 

### ISSUE THREAD

**Issue by juskoljo** [difi/ehf-postaward-g3#4]
Hi,

I'm unable to transform SCH to XSL due to this issue

https://github.com/anskaffelser/ehf-postaward-g3/blob/07f5078418dc43bca594020d46430389336cc062/rules/reminder-3.0/sch/EHF-REMINDER-3.0.sch#L24

BR,
Jussi

**Comment by klakegg** [comment]
Solved during build.
