### ISSUE TITLE
Determine the UblVersion for ehf:forward-billing:3.0

### ISSUE THREAD

**Issue by HarshaSuranjith** [difi/ehf-postaward-g3#5]
In EHF3 certain document types uses Ubl version 2.1 and some document types uses 2.2 (e.g. Invoice and CreditNote in forward-billing:3.0). Therefore Ublversion must be identified using the document contents.

Since UblVersionId is not included in the document anymore, how can we determine/extract UblVersion ? 

If not what is the alternative ?

**Comment by klakegg** [comment]
The UBL version is documented in the specifications:
https://vefa.difi.no/ehf/g3/forward-billing-3.0/guide/#_ubl_2_2
