### ISSUE TITLE
EHF Forward Billing 3.0: Issues with examplefiles, Schematron/validation rules and UBL version

### ISSUE THREAD

**Issue by sboklund** [difi/ehf-postaward-g3#6]
Hi,

Very nice to see this becoming its own, standalone format/specification!

We (Pagero) have had a look at this and have a few thoughts we´d like to raise...

**No. 1:** The example files ([found here](https://github.com/anskaffelser/ehf-postaward-g3/tree/master/docs/forward-billing-3.0/guide/example/energy)) contains some minor errors...

a. The `/(Invoice|CreditNote)/cac:AccountingCustomerParty/cac:Party/cbc:Name` is incorrectly placed, should be inside a `cac:PartyName`-segment. This error exists in all four testfiles.

b. In the CreditNote-examples, the xmlns-declaration incorrectly points to the Invoice-XSD: `<CreditNote xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"...`, it should point to the CreditNote: `<CreditNote xmlns="urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2"...`.

c. In the CreditNote-examples, `cbc:DueDate` should not be included according to the UBL XSD.

**No. 2:** Is the "PEPPOL-EN16931-R007"-rule expected to be "relaxed" in the PEPPOL BIS Billing 3.0 spring release?

Jan André Mærøe at Digdir told us that you do not NOT plan to release any "EHF Forward Billing 3.0"-specific Schematron-rules and that we should use the underlying PEPPOL BIS/EHF Billing 3.0 Schematron-rules... But after running some tests in different validators it appears there actually are some discrepancies in regards to the validation rules used. It appears Difi/DigDirs online validator recognizes the format as it´s own, separate "EHF Forward Billing 3.0 (Profile 08)" and all four UNEDITED testfiles (i.e. including the XSD-errors mentioned above, which looks to us as if the XSD-validation isn´t correctly performed) pass the validation without errors, whereas we, in both Validex´ and Philip Helger´s validators, get a couple of errors when using the PEPPOL BIS Billing 3.0 specification, in addition to the XSD-errors mentioned above...

Ignoring two errors related to invalid GLN (warning) and Norwegian ORGNR (fatal) in the examplefiles, the following error is going to be problematic for us:

Flag: fatal
Rule id: PEPPOL-EN16931-R007
Message: Business process MUST be in the format 'urn:fdc:peppol.eu:2017:poacc:billing:NN:1.0' where NN indicates the process number.
Location: `/(Invoice[1]|CreditNote[1])`

If this and/or any other of the validation rules from the "regular" PEPPOL BIS/EHF Billing 3.0 are to be adjusted/deviated from, we would ask that you please publish, support and maintain separate Schematron-files for the format as a whole. Otherwise we would have to introduce a step where we manually have to adjust the PEPPOL BIS/EHF Billing 3.0 Schematron-files, and this is something we (and hopefully most other APs) would like to avoid.

**No. 3:** Lastly, we believe that the use of UBL 2.2 in the EHF Forward Billing 3.0 is contradictory since the underlying Peppol BIS/EHF Billing 3.0 uses UBL 2.1.

Hope you understand, let me know if anything is unclear or if you have any questions!

Looking forward to your reply!

Sebastian Boklund
Pagero Group

**Comment by klakegg** [comment]
I don't see the problem of using UBL 2.2 in EHF Forward Billing 3.0.
